### ISSUE TITLE
Service does not respond when regex matched line occurs at the beginning of a gig long file

### ISSUE THREAD

**Issue by Kaustubh-cribl** [dleemath/cribl-takehome#1]
Service does not respond when regex matched line occurs at the beginning of a gig long file. Postman stays stuck at 'Sending request' for long long time. This is after increasing timeout to 500 seconds.

Acceptance criteria:

1. Service should respond within reasonable latency

<img width="1404" alt="Screenshot 2024-06-24 at 9 41 40 PM" src="https://github.com/dleemath/cribl-takehome/assets/171298919/e6d5eb1e-491f-406b-970a-d65234b88780">

**Comment by dleemath** [comment]
Since we need to scan the whole file, we may discuss the use case with/the trade of memory usage.

1. load the whole file with mmap for files <= 1G with regex in the request (for non-regex requests, keep the current chunk loading approach)
2. mmap + multi-threading to load chunk size of 1G/num of thread, however, this approach may complicate the reduce phase since we need to wait for each thread to complete to produce results in the correct order.

**Comment by Kaustubh-cribl** [comment]
How about if we relax regex matching to simple contains check, plus some other optimizations, and see if large files are within bounds of reasonable response times (say 30 seconds or so)?

**Comment by dleemath** [comment]
Turns out there is a bug in the chunk reading. 
Also increased chunk size and add chunk skipping for non found regex

**Comment by dleemath** [comment]
```
 ls -alth                                                                                                                                                                                 ✔ 
total 4609904
drwxr-xr-x  13 yifangl  staff   416B Jun 27 15:37 ..
drwxr-xr-x   6 yifangl  staff   192B Jun 27 15:31 .
-rw-r--r--   1 yifangl  staff   1.1G Jun 27 15:31 test_big.log
```

**Comment by dleemath** [comment]
<img width="886" alt="image" src="https://github.com/dleemath/cribl-takehome/assets/8453496/e82969c3-a225-4d40-94d7-45e1c1393e12">
